#!/bin/bash

out=cascadia_seis.ps 				# This will be the name of your map generated by this file
seis_data=NCEDC_Search_Results.dat			# ANSS earthquake catalog
topo=../../dems/greeceSRTM.grd			# ETOPO1 topography grid

north=42
south=34
east=29
west=19

tick='-B2/2WSen'

proj='-Jm24/37/1:6000000'


psbasemap -R$west/$east/$south/$north $proj $tick -P -Y12 -K > $out

makecpt -Crelief -T-8000/8000/500 -Z > topo.cpt

grdimage $topo -R -J -O -K -Ctopo.cpt   >> $out

pscoast -R -J -O -K -W2 -Df -Na -Ia -Lf-130.8/46/10/200+lkm >> $out

makecpt -Crainbow -T0/50/10 -Z > seis.cpt

awk '{print($4,$3,$5)}' $seis_data | psxy -R -J -O -K  -W.1 -Sc.1 -Cseis.cpt -H15 >> $out 

psscale -D0/3.2/6/1 -B10:Depth:/:km: -Cseis.cpt -O -K >> $out

psxy center.dat -R -J -O -K -W1 -Sc.3 -G255/0/0 >> $out
psxy center.dat -R -J -O -K -W5/255/0/0 >> $out

awk '{print($4,$3,$5)}' $seis_data | project -C21/36 -A45 -W-.2/.2 -L0/4 -H15 > projection.dat


east=25
west=21 
dmin=0 
dmax=50

proj=-JX15/-5
tick=-B1:Longitude:/10:Depth:WSen


awk '{print($6,$3)}' projection.dat | psxy -R$west/$east/$dmin/$dmax $proj $tick -W1 -Sc.2 -G200 -O  -Y-8 -P >> $out


# open $out
gs -sDEVICE=jpeg -dJPEGQ=100 -dNOPAUSE -dBATCH -dSAFER -r300 -sOutputFile=test.jpg $out


